config/routes.rb
Rails.application.routes.draw do

  get 'profiles/show/:id', to: 'profiles#show'

  devise_for :users

  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :login
    get 'register', to: 'devise/registrations#new', as: :register
    get 'logout', to: 'devise/sessions#destroy', as: :logout
    get 'account', to: 'devise/registrations#edit', as: :account
  end

  root to: "statuses#index"

  resources :statuses
  get 'new', to: 'statuses#new', as: :new

  get ':id', to: 'profiles#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, length: { minimum: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, :last_name, :profile_name, presence: true
  validates :profile_name, :email, uniqueness: { case_sensitive: false }, length: { minimum: 3 }

  has_many :statuses

  def full_name
    first_name + ' ' + last_name
  end
end

app/controllers/application_controller.rb
# Devise user authentication controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |params|
      params.permit(
        :email, :password, :password_confirmation, :first_name,
        :last_name, :profile_name
      )
    end
    devise_parameter_sanitizer.permit(:account_update) do |params|
      params.permit(
        :email, :password, :password_confirmation, :first_name,
        :last_name, :profile_name, :current_password
      )
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_profile_name(params[:id])
    @statuses = @user.statuses.all
  end
end

app/controllers/statuses_controller.rb
# Status/Statuses controller
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_status
    @status = Status.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def status_params
    params.require(:status).permit(:content, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_helper(type)
    case type
    when 'notice'
      'alert alert-success'
    when 'alert'
      'alert alert-danger'
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
  def gravatar_url(user)
    "https://s.gravatar.com/avatar/" + Digest::MD5.hexdigest(user.email.strip.downcase)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Treebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <!-- Fixed navbar -->
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Treebook', root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"> <%= link_to "All Statuses", root_path %></li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_user.full_name %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "My Account", account_path %></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><%= link_to "Logout", logout_path %></li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "login", login_path %></li>
              <li><%= link_to "Signup", register_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <div class="container theme-showcase" role="main">

    <% flash.each do |key, message| %>
        <div class="<%= flash_helper key %>">
            <button type="button" class="close" data-dismiss="alert"
             aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= message %>
        </div>
        <% end %>

  <%= yield %>

  </div>  <!-- /container -->

  </body>
</html>

app/views/profiles/show.html.erb
<h2>Statuses for</h2>

<div class="row">
  <div class="col-md-4">
    <legend><strong><%= @user.profile_name %></strong> (<%= @user.email %>)</legend>
    <% if @statuses %>
        <div class="well"><% @statuses.each do |s| %>
              <%= link_to s.content, status_path(s) %>
              <%= time_ago_in_words(s.created_at) %> ago <br />
          <% end %>
        </div>
    <% else %>
        <%= 'Not statuses' %>
    <% end %>
  </div>
</div>

app/views/statuses/_form.html.erb
<%= simple_form_for(status, html: { class: "form-horizontal" },
                    wrapper: :horizontal_form ) do |f| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.input :content, label: false %>
  <%= f.button :submit, class: "btn btn-large btn-success" %>
  <% end %>
  </div>
</div>

app/views/statuses/edit.html.erb
<div class="row">
  <div class="col-md-4 well">
    <legend><strong>Edit Status</strong></legend>

    <%= render 'form', status: @status %>

    <%= link_to 'Show', @status %>
  </div>
</div>

app/views/statuses/index.html.erb
<div class="page-header">
  <h1>Statuses</h1>
  <% if user_signed_in? %>
    <%= button_to 'New Status', new_path, method: :get, class: 'btn btn-large btn-success' %>
  <% end %>
</div>

   <% @statuses.reverse_each do |status| %>
    <div class="status">
      <div class="row">
        <div class="span">
            <div class="col-sm-1">
              <strong><%= status.user.profile_name %></strong> <br/>
              <%= image_tag gravatar_url(status.user) %>
            </div>
            <div class="col-sm-2">
              <p>
              <p><%= status.content %></p>
              </p>
            <div class="meta">
                <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
                <span class="admin">
                   | <%= link_to "Edit", edit_status_path(status) %> |
                  <%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure?" } %>
                </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/statuses/new.html.erb
<div class="row">
  <div class="col-md-4 well">
    <legend><strong>New Status</strong></legend>

        <%= render 'form', status: @status %>

    </div>
</div>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-4 well">
    <legend><strong>Show Status</strong></legend>

    <h4>
      <%= @status.user.full_name %>
    </h4>
    <h5>
      <%= @status.content %>
    </h5>
    <br />
    <%= link_to 'Edit', edit_status_path(@status), class: "btn btn-large btn-success" %>
    <%= link_to 'Delete', @status, method: :delete, data: { confirm: "Are you sure?" },
            class: 'btn btn-large btn-warning'%>
  </div>
</div>